stratum_listen: ":4444"
tls_cert_path: ""
tls_key_path: ""
node_rpc_url: "http://testuser:testpass@127.0.0.1:18232"
metrics_listen: ":9100"
nats_url: ""
postgres_dsn: ""
clickhouse_dsn: ""
pool_fee_bps: 100
donation_default: false
vardiff_target_ms: 800
vardiff_retarget_secs: 30
default_difficulty: 1
pps_reward_per_diff: 0.0
block_confirmations: 10
payout_threshold: 0.1
payout_batch_cron: "@daily"
